### ISSUE TITLE
Swiper Component not working

### ISSUE THREAD

**Issue by mmchokor** [mmchokor/house_marketplace#1]
I have already posted a question on StackOverflow at this [**Link**](https://stackoverflow.com/questions/72665155/swiper-component-not-working-in-react-and-throwing-erros). 
But in short, whenever I try to use the Swiper Component, it doesn't work and throw errors in the console (included in the StackOverflow question), I tried many version of this component but nothing seems to work copied the code from the original project, from the docs, still no luck there.
The component is used in the following files Listing.jsx and Explore.jsx, which are both located ./src/pages/

**Comment by developer-sidani** [comment]
@mmchokor The problem is resulted with the initiation of swiper, have you tried a different version of swiper?

I checked your dependencies and it seems like you have a different version of swiper than the one traversery is using.

Your version:   `  "swiper": "^6.8.4",`
Traversary's version:  `"swiper": "^6.8.1",`


Try switching the version or read the documentation of swiper to know more about the resulted error

**Comment by mmchokor** [comment]
> I checked your dependencies and it seems like you have a different version of swiper than the one traversery is using.

Yes, while I was following along in the tutorial he specified a certain version of the swiper component, i installed that specific version then and yet still didn't work so i tried many different version, and same result

**Comment by developer-sidani** [comment]
@mmchokor It seems like there are some missing packages for swiper.

By default Swiper React uses core version of Swiper (without any additional modules). If you want to use Navigation, Pagination and [other modules](https://swiperjs.com/swiper-api/#custom-build), you have to install them first.

**Comment by mmchokor** [comment]
@developer-sidani I didn't understand what you mean, I followed all the steps of Brad in his videos and he only installed the swiper component, and when that didn't work I read the documentation and followed the steps but all aren't working.

I will try to search for alternative components like Swiper. Thank you for the help

**Comment by mmchokor** [comment]
Fixed it by using another package called react-slick
